server:
  port: 9999

remote:
  host: 'localhost'
  port: 25575
  password: '123123'


spring:
  application:
    name: web-rcon
  mvc:
    format:
      date: yyyy-MM-dd
      date-time: yyyy-MM-dd HH:mm:ss
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite::resource/sqlite/database.db
    username:
    password:
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml

